export const CREATE_CART = "CREATE_CART";
export const DELETE_CART = "DELETE_CART";
export const GET_CART = "GET_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_MULTIPLY = "ADD_TO_CART_MULTIPLY";
export const DECREASE_ITEM = "DECREASE_ITEM";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const SET_IS_LOADING_CART = "SET_IS_LOADING_CART";
