export const ADD_COMMENT = "ADD_COMMENT";
export const GET_COMMENTS_OF_PRODUCT = "GET_COMMENTS_OF_PRODUCT";
export const GET_ALL_COMMENTS = "GET_ALL_COMMENTS";
export const DELETE_ONE_COMMENTS = "DELETE_ONE_COMMENTS";